### ISSUE TITLE
Install instructions for failed builds

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#103]
Is it anyhow useful to show install instructions for builds that failed?

Example: https://dashboard.packit.dev/results/copr-builds/110905
![Screenshot from 2021-05-14 11-00-00](https://user-images.githubusercontent.com/20214043/118247646-b25c6280-b4a3-11eb-8408-12959116e6c5.png)

**Comment by mfocko** [comment]
will have a look
