### ISSUE TITLE
Make the URL of Testing Farm results more visible

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#107]
After helping someone with the TF today I feel like It's now not clear where a user can find more details about the TF result.

![Screenshot from 2021-05-21 18-29-27](https://user-images.githubusercontent.com/20214043/119169704-9ee06700-ba62-11eb-8322-70b863da1895.png)

My concerns:
* People don't need to know doest the Testing-Farm mean.
* The term `result` is used as a link to the Copr build, not for the actual Test results.
* The field names are not consistent (with or without URL).

AC:
* [ ] Remove the "Testing Farm URL" field, and place the link on the *Status* text, that is "passed" or "failed" will be also a link to the testing farm page.
* [ ] Instead of "Copr build: Results" say: "Copr build: Details"

*Take the acceptance criteria as a suggestion.*

**Comment by mfocko** [comment]
Current design: as seen in the description
Cards: ![](https://i.imgur.com/OMJKmZJ.png)
Description list: ![](https://i.imgur.com/kvAp5jj.png)
Grid and cards: ![](https://i.imgur.com/yLLqDlI.png)

Which one would we prefer?

**Comment by lachmanfrantisek** [comment]
To me, all the new variants look a bit messy. Is it only me?

**Comment by jpopelka** [comment]
I like the last one (grid & cards) the most but I don't see how it's supposed to fix [the issue](https://github.com/packit/dashboard/issues/107#issue-898233407). (did we discuss that on grooming and I just forgot?)

**Comment by csomh** [comment]
Yeah, I also think the current design has the best structure. Improving the wording should help with avoiding confusion.
