### ISSUE TITLE
Build logs should use use browser wrapping

### ISSUE THREAD

**Issue by ssbarnea** [packit/dashboard#120]
At this moment the build logs are not wrapped to browser window size and that makes it quite hard to read essential information from lines that are longer than the window.

https://dashboard.packit.dev/results/srpm-builds/28981

This [css hack](https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag) seems to achieve the desired wrapping:
```
code {
    white-space: pre-wrap;
}
```

This behavior would also match what a normal user terminal would see, as terminals do not usually hide the long lines and do wrap them instead.

**Comment by TomasTomecek** [comment]
Thanks for opening the issue, indeed a good suggestion. I'm also wondering if patternfly has native support for terminal-like outputs.

**Comment by ssbarnea** [comment]
Does https://github.com/patternfly/patternfly-design/issues/955 look familiar? ;) -- apparently things are moving slowly but in good direction.

**Comment by TomasTomecek** [comment]
@ssbarnea nice!!

I can see some related PRs were already merged, e.g. https://github.com/patternfly/patternfly/pull/4029

shall we use that?

**Comment by ssbarnea** [comment]
If it was released I would clearly take a look at at it. Still, there is something confusing me about patternfly release process, apparently all tags are marked as prerelease when I look at https://github.com/patternfly/patternfly/tags

**Comment by TomasTomecek** [comment]
@ssbarnea: @mfocko is already busy with some updates to the log-viewer as you can see above :) stay tuned!

**Comment by mfocko** [comment]
Small update on the issue: I have tried the LogViewer, spotted 2 issues:

1. empty lines in logs made huge dead space, which I have fixed in upstream already
2. each line is estimated 60px height; that *at least from my perspective* is bigger issue than the logs not being wrapped, I will try to fix that in the upstream too

After fixing the 2nd issue we should be good to go :)
