### ISSUE TITLE
Single pipeline result page

### ISSUE THREAD

**Issue by mfocko** [packit/dashboard#130]
Create a result page for single pipeline (ideally with merged runs). Try to use as much as possible from the result components used so far.

Edit:
- make sure that all builds and tests are included in the view

**Comment by TomasTomecek** [comment]
Yes please!! Ideally with links to builds, logs, test runs for all the jobs; that would be mindblowing.

**Comment by Venefilyn** [comment]
Yes, closing! :partying_face:
