### ISSUE TITLE
PR/MR description in the pipeline view

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#133]
I spent the last day looking a lot into the `Pipelines` view and it would be really nice to get a PR/MR description when hovering on the PR/MR link.

Something like this:
![Screenshot from 2021-08-02 22-01-05](https://user-images.githubusercontent.com/20214043/127917017-48bbcf78-aa58-4e65-a26d-d9a2e39cc84a.png)

**Comment by TomasTomecek** [comment]
Hm, would we have to provide it via packit's API or fetch from github on the client?

**Comment by mfocko** [comment]
I think the biggest issue when running client-side is GitHub's _rate-limiting_. They do a nice thumbnail preview if you send link in Telegram, Discord, etc. So it may be worth a try to embed thumbnail into the tooltip of the link. However that might fail miserably :D

**Comment by TomasTomecek** [comment]
worth trying! :)
