### ISSUE TITLE
Copr → Packit Dashboard integration

### ISSUE THREAD

**Issue by TomasTomecek** [packit/dashboard#151]
We already have Packit Dashboard ➡️ Copr integration. This is a tracking issue to cover the other side: being able to go from Copr web interface to Packit Dasboard (or GitHub).

Context:
https://pagure.io/copr/copr/issue/1890
https://pagure.io/copr/copr/pull-request/1970

Let's brainstorm some ideas here.

CC @xsuchy @frostyx @praiskup

**Comment by praiskup** [comment]
The issue/PR you mentioned is just about a single-place ad, basically.  No problem there of course, but is that what you want to brainstorm about?

If you want more fine-grained links, ... what would be an example Packit dashboard link Copr should point to (from a particular project or even build)?

**Comment by TomasTomecek** [comment]
> The issue/PR you mentioned is just about a single-place ad, basically. No problem there of course, but is that what you want to brainstorm about?

This issue is a follow-up to Mirek's point on today's meeting :) that one of the cards could indeed point to our dashboard, or something like that.
 
> If you want more fine-grained links, ... what would be an example Packit dashboard link Copr should point to (from a particular project or even build)?

Nice, this is the discussion I wanted to start, thanks Pavel. Build/project links sound like a great start since people would have an easy way to access their PRs and test runs in Testing Farm.

Would we enable that for all the repos which use packit (how would we know?) or just those in our namespace for the CI-like builds?

**Comment by praiskup** [comment]
There's currently the project description field, which is entirely under Packit's (user) control.
That's IMO a good thing because Copr doesn't have to add a special logic or something.
Do you want to have some "description" field per/build, too?

> what would be an example Packit dashboard link Copr should point to?

Do you have such an example?  I don't have the rough idea about what page should point to
which page :-)

**Comment by TomasTomecek** [comment]
Pavel, that's actually a very good point: we could start setting those links ourselves.

https://copr.fedorainfracloud.org/coprs/packit/packit-ogr-653/ → https://dashboard.packit.dev/projects/github.com/packit/ogr
or even better to the specific pipeline run (being worked on here https://github.com/packit/dashboard/pull/135 )

**Comment by csomh** [comment]
We decided to close this in favour of other work. If you still think it's important, please re-open it.
