### ISSUE TITLE
View for propose-downstream

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#155]
Provide a view for the `propose-downstream` job using packit/packit-service#1292

Users want to see:
* Upstream event that was used to trigger the job.
* State the job is in.
* Logs.
* Links to the downstream PRs.

**Comment by prathamaror** [comment]
I would like to work on this issue

**Comment by lachmanfrantisek** [comment]
@prathamaror Hello. That would be nice!

Just be aware that packit/packit-service#1292 is not ready yet and needs to be done to make this work. (But you can at least start I think.)

[Here](https://github.com/packit/dashboard/blob/main/CONTRIBUTING.md) is our contribution guide. Let us know if you need some help.
