### ISSUE TITLE
Figure out how to "insert" fake data for propose-downstream jobs.

### ISSUE THREAD

**Issue by nikromen** [packit/dashboard#173]
As I mentioned in #168 current "solution" of inserting fake data to dashboard running on localhost is really poor. We need to figure out better way of "inserting" fake data to propose-downstream jobs (and not only for them).

**Comment by TomasTomecek** [comment]
we should already have some data in the production database, right?

is this still needed or do you think it's still worth having this mechanism in place?

**Comment by lachmanfrantisek** [comment]
Maybe to make it clear, one can dump the data from stg/prod and fill it into the locally deployed database. It works quite well for testing migrations as well.

**Comment by TomasTomecek** [comment]
so at least we should have such process documented, especially now when our prod database is being backed up
