### ISSUE TITLE
Make our Grafana dashboard with adoption metrics freely available

### ISSUE THREAD

**Issue by nikromen** [packit/dashboard#185]
Do this once [packit-service#1567](https://github.com/packit/packit-service/issues/1567) is done.

Make our adoption metrics that we have implemented and displayed via Grafana available for everyone. There is [how we want to do that](https://github.com/packit/research/blob/main/adoption-metrics/implementation.md#but--2). It may be tricky but hopefully the steps provided in the link above will work.

TODO:
- [ ] Make subpage on our dashboard - available on the left menu.
- [ ] This subpage will contain rendered graphs shared from Grafana. Each graph have to be (probably) rendered individually - we don't want to share everything in our Grafana dashboard but only some graphs.
- [ ] To render the graphs we have to install the [Grafana image renderer](https://grafana.com/grafana/plugins/grafana-image-renderer/)
- [ ] [Provide link to Grafana/Dashboard on packit.dev menu](https://github.com/packit/research/blob/main/adoption-metrics/implementation.md#provide-link-to-grafanadashboard-on-packitdev-menu)

**Comment by lachmanfrantisek** [comment]
Replaced by the dashboard usage page.
