### ISSUE TITLE
Paginated tables has confusing sorting

### ISSUE THREAD

**Issue by SpyTec** [packit/dashboard#210]
The paginated tables for Copr, Koji SRPM, Test Runs, and Propose Downstreams have columns that allow sorting. Problem is that these only sort the fetched dataset and does not fetch from the API.

Given that the API has no sorting on the data this shouldn't be implemented on the dashboard either as the sorting would be kind of inaccurate or difficult to work with

Instead, sorting should be removed until it is available in the API for proper fetching

(also every column with tags in them like for Koji's Target column doesn't sort correctly anyway)

**Comment by TomasTomecek** [comment]
completely agree that the sorting should be done in the API
