### ISSUE TITLE
Introduce loading indicator for paginated tables when Load More has been clicked 

### ISSUE THREAD

**Issue by SpyTec** [packit/dashboard#211]
When you click Load More there is no indicator that something is going on or that it has been clicked. This means you don't know if something is going on and you may click it again it will start loading a new page and the previous one being fetched won't be updated

It creates weird scenarios that becomes a bit troublesome and it should be improved to prevent mistakes like this so data isn't missed

**Comment by TomasTomecek** [comment]
Completely agree! I personally love sites where they load more as you scroll down, that would be mindblowing to have.

Having a "loading" indicator would be a huge step up! Thank you for pointing this out.

**Comment by SpyTec** [comment]
> I personally love sites where they load more as you scroll down, that would be mindblowing to have.

I could make that - infinite scrolling - happen as well without even seeing the bottom of the page before next page is loaded

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
https://www.npmjs.com/package/react-intersection-observer
