### ISSUE TITLE
Proposal to use React Query

### ISSUE THREAD

**Issue by SpyTec** [packit/dashboard#212]
For fetching data from an API it is always the same concerns on how to approach it. There are a few workarounds in the code to get initial fetch to work and so on, but this will cause unnecessary calls and renders. There are libraries specifically for helping with fetching data in functional components

In Telltale I made use of React Query and found it to be super useful when doing anything with multiple parameters or pagination in general. It also supports caching and a bunch of other nice things

Is this something we should consider using when updating existing queries or writing new ones?
https://react-query-v3.tanstack.com/

**Comment by majamassarini** [comment]
The linked PR looks amazing, I move this one to the backlog.
Thank you for your help!
