### ISSUE TITLE
Can't base image on F38 due to missing nodejs:18 module

### ISSUE THREAD

**Issue by jpopelka** [packit/dashboard#247]
### Description

We're using [nodejs:18 module](https://github.com/packit/dashboard/blob/main/files/ansible/install-deps.yaml#L9).

Currently, there's no `nodejs:18` module in F38, only `nodejs:16`, see `podman run -ti --rm fedora:38 dnf module list`.
Does anyone know where to request it?

I'm also wondering what's the difference between the `nodejs:18` module and `nodejs` rpm which also looks like version 18.
BTW, there's also `nodejs20` in both F37 and F38, can't we use that?

### Benefit

We can bump base image to F38

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by csomh** [comment]
I seems (3cd34b7) we started using the module to work around some crypto issue in Fedora 36. It should be okay to use the `nodejs` rpm if this got solved in the meantime.

**Comment by jpopelka** [comment]
#258 is the way, closing
