### ISSUE TITLE
6. Turn Pipeline ID into link to Testing Farm results

### ISSUE THREAD

**Issue by jpopelka** [packit/dashboard#276]
![Screenshot from 2023-06-15 16-32-44](https://github.com/packit/dashboard/assets/288686/c047315d-6900-467e-b420-c7a7d4cb51f8)

replace bd626b8b-e988-4eca-b5d6-7be68118eb32 -> [bd626b8b-e988-4eca-b5d6-7be68118eb32](https://artifacts.dev.testing-farm.io/bd626b8b-e988-4eca-b5d6-7be68118eb32/)

hint: `curl -X 'GET' 'https://stg.packit.dev/api/testing-farm/17812' -H 'accept: application/json'`

**Comment by mfocko** [comment]
Status is the link to it... It's a bit weird compared to the Copr, also in the tables. Not sure why it's like that though

**Comment by jpopelka** [comment]
Correct, perhaps the status (`passed` on the screenshot) shouldn't be a link?
