### ISSUE TITLE
Crash with TypeError: e.trigger.builds is undefined

### ISSUE THREAD

**Issue by danmyway** [packit/dashboard#319]
Reproducer:
Access https://dashboard.packit.dev/projects/github.com/oamg/convert2rhel and click Load more.

Error message:
TypeError: e.trigger.builds is undefined

**Comment by lbarcziova** [comment]
Thanks for reporting! The cause of this is https://github.com/packit/packit-service/issues/2153 so the progress will be tracked there.

**Comment by mfocko** [comment]
Can we close as the root cause has been resolved?

**Comment by mfocko** [comment]
> What do you mean?

OH! it's the `s.map` from the other issue you just linked

**Comment by lbarcziova** [comment]
The fix is now in production, closing.
