### ISSUE TITLE
Dashboard crashed

### ISSUE THREAD

**Issue by mulkieran** [packit/dashboard#322]
Entering URL https://dashboard.packit.dev/projects/github.com/stratis-storage/stratis-cli in my browser's field for URLs causes this.

**Comment by mulkieran** [comment]
w/ Python error: ```TypeError: s.map is not a function```

**Comment by lbarcziova** [comment]
hi! Thanks for reporting this. 

It looks like this is similar as #319 and caused by packit/packit-service#2153

**Comment by lbarcziova** [comment]
The fix is now in production, closing.
