### ISSUE TITLE
Ability to view individual pipelines

### ISSUE THREAD

**Issue by Venefilyn** [packit/dashboard#340]
### Description

Going to Pipelines currently shows all Pipelines, though the API does provide the Pipeline ID as well as an API endpoint for getting specific Pipeline runs

We could change the existing structure as it is a bit confusing with the Trigger being an external link instead of linking within the Packit website

Changing it to be like this suggestion would mean we have both internal and external link without having to confuse people

(1) is the internal link to `/pipelines/1234`
(2) is the external trigger link that goes to the forge, e.g. `https://github.com/packit/dashboard/pull/336`

![image on how it could work](https://github.com/packit/dashboard/assets/6598829/4da8a741-e7aa-4c69-98d3-55515e096194)

(structure/style from the image might need an improvement)

> **Note**
> This would also get the same sort of change to the different Job tables

### Benefit

Be able to link to specific Pipelines

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [x] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by SpyTec** [comment]
@lachmanfrantisek I would have put the `namespace/project#123` as internal link since the pipeline view for it would be for that specific PR right?

But having some consistent external link style would be handy otherwise

**Comment by lachmanfrantisek** [comment]
> But having some consistent external link style would be handy otherwise

Maybe prefix the link with different icons? Or use the `external-link` icon from Font Awesome just for the external links?

**Comment by SpyTec** [comment]
RH Icons has an external link already we can utilize, that's the icon in the picture in the original post

I will probably end up poking someone with UX experience to take a look

**Comment by lachmanfrantisek** [comment]
> I will probably end up poking someone with UX experience to take a look

Nice! Thanks!

This is probably not a Packit-specific issue and should have already been discussed.

**Comment by SpyTec** [comment]
Got an answer from someone very proficent in UX and was told this:

> The only thing I’ve seen is the first column is the pipeline run “name” that is an internal link to a Details page with the pipeline visualization and logs. Then there is a second column with the commit name/value that links externally to commit hash (link text + external link icon)

Side note, they showcased this for a separate product who uses pipelines. Could possibly be something we can use here and there

![image](https://github.com/packit/dashboard/assets/6598829/7af1d1ac-aabe-4d63-a9a5-6ebf711d1f62)
