### ISSUE TITLE
Charts for jobs

### ISSUE THREAD

**Issue by csomh** [packit/dashboard#37]
The jobs page in Dashboard should show some useful charts.

TODO for @csomh to figure out what these should be.

**Comment by lachmanfrantisek** [comment]
@IceWreck @csomh Do we still want it? Do we want to describe this more specifically?

**Comment by csomh** [comment]
Yes, I think this would be useful to have. But I have no clue when I'll have time to describe this in more detail.

The first chart could be just visualising the rows in the different tabs on the *Jobs* page as a line-chart, as *time / number of jobs submitted during a period*. *Period* could be something adjustable, like: hour, day, week, month...

**Comment by lachmanfrantisek** [comment]
Let's leave it open one more time. We might want to have some independent tasks here for external contributors...
