### ISSUE TITLE
Charts for projects

### ISSUE THREAD

**Issue by csomh** [packit/dashboard#38]
The project page in Dashboard should show some useful charts.

TODO for @csomh to figure out what these should be.

**Comment by lachmanfrantisek** [comment]
@IceWreck Do you still want to work on it? (I know GSOC is over, but I am asking since you are assigned and maybe still interested..;)

**Comment by IceWreck** [comment]
We couldnt decide what we actually needed graphs/charts for where they would be useful at that time.

And I'm working on #64 rn, given it two attempts now, had some progress but am still struggling with async issues during implementation. Will give it another try this weekend. On the plus side, Ive learnt a lot about how async stuff works in JS.

**Comment by lachmanfrantisek** [comment]
@IceWreck thanks a look, no worries. Take your time. We're glad that you still collaborate with us..;)

**Comment by lachmanfrantisek** [comment]
Same as the other, similar, one:

> Let's leave it open one more time. We might want to have some independent tasks here for external contributors...
