### ISSUE TITLE
View for OpenScanHub results

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#441]
It would be nice to present people results from the analysis including the relation to other related jobs (like SRPM/RPM) build.

This would most probably require a reporting mechanism to be implemented.
(Currently, Packit only triggers the scan.)

We might also want to think about this as part of Project Mycorrhisa, ping @Venefilyn .

todo
* [x] add needed information to the service API
* [x] implement a basic view for the scan

**Comment by lachmanfrantisek** [comment]
We also need to think about what needs to be displayed on Packit side and what (if) needs to be on OSH only.

**Comment by siteshwar** [comment]
As mentioned by @kdudka in https://github.com/packit/packit/discussions/2371#discussioncomment-10398054, this needs to be implemented on the Packit side.

As per my understanding, the workflow should look like:

- Packit submits the scan to OSH, and waits for the scan to finish.
- If the scan was successful, download `scan-results.js` and convert it to SARIF through `csgrep --mode=sarif`.
- Upload the SARIF output to CodeQL, or a similar service that can present the results in a user friendly way.
- Link the user to the report through GitHub actions, or similar CI job.

@davidmalcolm Let us know if you have any suggestions here. Thanks!

**Comment by siteshwar** [comment]
> We might also want to think about this as part of Project Mycorrhisa, ping @Venefilyn .

As I understand, it is Project Mycorrhiza and its a terrible name.

**Comment by lachmanfrantisek** [comment]
> As I understand, it is Project Mycorrhiza and its a terrible name.

I like the meaning but always struggle with the spelling..;-) Btw. we are collecting use cases people want to see help with here: https://packit.limesurvey.net/project-mycorrhiza

**Comment by lachmanfrantisek** [comment]
> * Packit submits the scan to OSH, and waits for the scan to finish.

@siteshwar btw, for this, we would appreciate messages coming to the Fedora message bus to avoid busy-wait which is really hard to do with the the current Packit's event-driven architecture. Do you think it's realistic to do?

Related issues about this:
* https://github.com/openscanhub/fedora-infra/issues/3
* https://pagure.io/fedora-infrastructure/issue/11853

**Comment by siteshwar** [comment]
> @siteshwar btw, for this, we would appreciate messages coming to the Fedora message bus to avoid busy-wait which is really hard to do with the the current Packit's event-driven architecture. Do you think it's realistic to do?

It is in my todo list. I would get back to it at some point in future.

**Comment by davidmalcolm** [comment]
> As mentioned by @kdudka in [packit/packit#2371 (reply in thread)](https://github.com/packit/packit/discussions/2371#discussioncomment-10398054), this needs to be implemented on the Packit side.
> 
> As per my understanding, the workflow should look like:
> 
>     * Packit submits the scan to OSH, and waits for the scan to finish.
> 
>     * If the scan was successful, download `scan-results.js` and convert it to SARIF through `csgrep --mode=sarif`.
> 
>     * Upload the SARIF output to CodeQL, or a similar service that can present the results in a user friendly way.
> 
>     * Link the user to the report through GitHub actions, or similar CI job.
> 
> 
> @davidmalcolm Let us know if you have any suggestions here. Thanks!

@siteshwar I confess my knowledge here is mostly on the diagnostics and SARIF **generation** side, less on filtering, presentation, etc.  I haven't played around with CodeQL yet; the pertinent docs would appear to be [here](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning).  I notice that they are using a few non-standard properties via property bags.  FWIW I regularly meet a CodeQL representative at the monthly OASIS SARIF TC meetings.

I'm nervous that going from, say GCC SARIF output to scan-results.js then back to SARIF might lose information.  Ideally we'd use SARIF throughout the process to keep as much info as possible (perhaps using property bags if there's anything that OSH wants to capture that isn't yet expressible in SARIF).  I'm familiar with a large subset of SARIF 2.1.0, so let me know if you have any questions about it.

**Comment by davidmalcolm** [comment]
@siteshwar Also, please note that (with my upstream GCC hat on), I regard GCC's "json" diagnostic output format to be "legacy"; all of my future development for machine-readable diagnostics is on its SARIF output format instead.  See https://gcc.gnu.org/wiki/SARIF for details on GCC's SARIF support, bug tracking, etc.

**Comment by kdudka** [comment]
@davidmalcolm OSH still captures the plain-text format of GCC diagnostics.  Although [csdiff](https://github.com/csutils/csdiff) supports all the three formats (plain-text, JSON, SARIF), it is not easy to migrate [csmock-plugin-gcc](https://github.com/csutils/csmock/blob/main/py/plugins/gcc.py) to the newer diagnostic formats.  As it is implemented now, the diagnostic output from all GCC processes is written to a single text file.  This works well for the plain-text format but not for the JSON-based format because concatenation of multiple JSON files is not a valid JSON.

Can GCC write a separate SARIF file to a specified directory for each invocation?  Something like `valgrind --xml-file=${dir}-%p-%n.xml ...`?  I think something like that would ease the transition of OSH to GCC's SARIF output...

**Comment by siteshwar** [comment]
> BTW, which version of GCC are you using?

The scans that are run through Packit are run on rawhide, so we use the same version of gcc as available in rawhide. Currently it is `14.1.1-7.fc41`, it can be actually see in the [stdout.log](https://openscanhub.fedoraproject.org/task/7651/log/stdout.log) of any scan.

**Comment by siteshwar** [comment]
> * Upload the SARIF output to CodeQL, or a similar service that can present the results in a user friendly way.

There is a [limit of 10 MB](https://docs.github.com/en/code-security/code-scanning/troubleshooting-sarif-uploads/file-too-large) on the results file. The SARIF file should be compressed before being uploaded.

**Comment by Venefilyn** [comment]
> * Upload the SARIF output to CodeQL, or a similar service that can present the results in a user friendly way.

I think outputting it with CodeQL would be great to keep things within GitHub. As for the dashboard we could make use of the SARIF output as well, for that I ask that packit-service can indicate in a response that a SARIF file exists or is being generated, and create a new endpoint to return the SARIF results

Given SARIF has a schema it should be relatively trivial to handle it in the dashboard as we can just generate types to make things easier for us through something like https://www.npmjs.com/package/@types/sarif/v/2.1.5

> > We might also want to think about this as part of Project Mycorrhisa, ping @Venefilyn .
> 
> As I understand, it is Project Mycorrhiza and its a terrible name.

It's a project/WG name for an idea! It's a good name :wink:

**Comment by lbarcziova** [comment]
I have started looking into the implementation details of this and have a few things to discuss/confirm first:
- is it ok if we focus on and display only the newly found defects, i.e. `added.js`? (there is also the general results file and fixed defects)
- before implementing the conversion to SARIF on our (Packit) side, I wanted to confirm whether this functionality doesn't generally make more sense to be in OSH directly, could other OSH users benefit from this as well?
- displaying of the SARIF on Packit's side: I agree with @Venefilyn point, Packit isn't serving GitHub only (even though most of our users are here), so it would be nice to have a general solution for displaying the SARIF on our dashboard, I haven't looked into the implementation details of that yet. But I wanted to confirm we want to have 2 ways of displaying the results - both on dashboard and in GitHub UI. GitHub's functionality for this looks really nice and for GitHub users would be great, from what I checked we would upload the SARIF using [this endpoint](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data) and for that we would need to update permissions for our app regarding `Code scanning alerts`  (see [docs](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-code-scanning-alerts)).

**Comment by siteshwar** [comment]
> I have started looking into the implementation details of this and have a few things to discuss/confirm first:
> 
> * is it ok if we focus on and display only the newly found defects, i.e. `added.js`? (there is also the general results file and fixed defects)

Yes, we should just point out new findings. 

> * before implementing the conversion to SARIF on our (Packit) side, I wanted to confirm whether this functionality doesn't generally make more sense to be in OSH directly, could other OSH users benefit from this as well?

@kdudka Shall this be done from OSH side?

> * displaying of the SARIF on Packit's side: I agree with @Venefilyn point, Packit isn't serving GitHub only (even though most of our users are here), so it would be nice to have a general solution for displaying the SARIF on our dashboard, I haven't looked into the implementation details of that yet. But I wanted to confirm we want to have 2 ways of displaying the results - both on dashboard and in GitHub UI. GitHub's functionality for this looks really nice and for GitHub users would be great, from what I checked we would upload the SARIF using [this endpoint](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#upload-an-analysis-as-sarif-data) and for that we would need to update permissions for our app regarding `Code scanning alerts`  (see [docs](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-code-scanning-alerts)).

I am fine with using Packit dashboard, as long as it enforces an action from users on new findings.

**Comment by lbarcziova** [comment]
Outcomes from our arch meeting: we will start for now with just a simple view in our dashboard (=> no need to store the SARIF at our DB for now) and try to integrate the GitHub SARIF support. GitLab doesn't seem to have something similarly straightforward, but I will have a look into possible alternatives.

**Comment by kdudka** [comment]
>> before implementing the conversion to SARIF on our (Packit) side, I wanted to confirm whether this functionality doesn't generally make more sense to be in OSH directly, could other OSH users benefit from this as well?
>
> @kdudka Shall this be done from OSH side?

@siteshwar This is being discussed repeatedly.  Extending `csmock` to (optionally) produce a SARIF file for each scan is trivial but it will significantly increase the storage size needed for scan results.  Another solution would be to produce SARIF files per request dynamically server-side, either from the simple JSON-encoded scan results, or from compressed SARIF files.

**Comment by Venefilyn** [comment]
For the osh API, can we get [access-control-allow-origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) enabled so we can embed the results?

**Comment by lbarcziova** [comment]
Outcomes from our today's sync with @lachmanfrantisek @siteshwar and @kdudka: uploading SARIFs to GitHub currently doesn't provide the additional benefit of code annotation as SRPM and RPM building changes the source code so the mapping back to get from the analysis result code placement to the source code would need to be implemented, which seems like a non-trivial thing, an example of this (using code from packit/packit-service#2621):

![Snímka obrazovky z 2024-11-07 11-48-06](https://github.com/user-attachments/assets/30f0fef1-3ee5-4876-9c36-5ad7bee17294)


With packit/packit-service#2622 we have improved the reporting now so that we report directly in GitHub whether/how many of new defects were identified. There is also a view in our dashboard now.
