### ISSUE TITLE
Use pending icon for pending states

### ISSUE THREAD

**Issue by QuLogic** [packit/dashboard#460]
### Description

Currently if a job is in progress, it has a sort of "i" icon:
![image](https://github.com/user-attachments/assets/d003dbf5-ab96-406e-8913-f8f9043447a1)
This looks very similar to the error icon:
![image](https://github.com/user-attachments/assets/80627259-8847-4221-b3c9-392fd86642e9)
Both appear as bold vertical bars, with maybe a pixel gap somewhere.

As neither of these actually directly display the state directly (you need to hover to get the tooltip), and the only other differentiation is the colour, it's difficult to realize the difference between them.

It would perhaps be better to use the `pficon-pending` or `pficon-in-progress` icons, as in:
https://www.patternfly.org/components/progress-stepper/#with-custom-icons

### Benefit

Clearer differentiation between job states.

### Workaround

- [ ] There is an existing workaround that can be used until this feature is implemented.

### Participation

- [ ] I am willing to submit a pull request for this issue. (Packit team is happy to help!)

**Comment by Venefilyn** [comment]
I agree this would be a great thing to change as they're very similar. I'll get a PR up today to fix it if possible! Pending icon could work, I'll double-check with other icons too but leaning on this one
