### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by dhodovsk** [packit/dashboard#5]
Dashboard can be moody - The requests fail with Connection error sometimes: 
```
127.0.0.1 - - [27/Jan/2020 16:39:33] "GET /projects/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:34] "GET /projects/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:34] "GET /projects/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:34] "GET /projects/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dhodovsk/repos/github.com/packit-service/dashboard/main.py", line 76, in projects
    for build in all_from(f"{API_URL}/copr-builds"):
  File "/home/dhodovsk/repos/github.com/packit-service/dashboard/main.py", line 64, in all_from
    page = return_json(url_, method, **kwargs)
  File "/home/dhodovsk/repos/github.com/packit-service/dashboard/main.py", line 37, in return_json
    response = requests.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 16:39:56] "GET /projects/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by jpopelka** [comment]
My guess is that it's because getting all the data from Redis takes too long - we just have to stop abusing Redis and store the data in Postgresql.

**Comment by maze-runnar** [comment]
@dhodovsk @jpopelka I want to work on this project for GsoC . Is there any dedicated channel for this project?

**Comment by maze-runnar** [comment]
I am good in Python, Flask, python, REST API, webdesign (UI/UX specialized). I am good to start with the project but there is not much info in readme file, where could I find the detailed info about the project about setup and other.

**Comment by lachmanfrantisek** [comment]
@maze-runnar 

Thanks for your interest in the task!

Ideally, ping @csomh, mentor of the task, on email (hcsomort@redhat.com) and we will send you more information where/how to start.

Since Hunor is out for some days, add me (flachman@redhat.com) to CC so I can send you the info sooner.

**Comment by maze-runnar** [comment]
Thanks @lachmanfrantisek .

**Comment by maze-runnar** [comment]
@lachmanfrantisek , can i please add you to gitter or only IRC?

**Comment by lachmanfrantisek** [comment]
> @lachmanfrantisek , can i please add you to gitter or only IRC?

For initial contact, please use an email, since we have all the info and useful links prepared in the form of an email.

Otherwise,  you can also easily reach me [on Telegram](https://t.me/lachmanfrantisek). Another option is IRC on Freenode in the #packit or #fedora-summer-coding channels. I’m usually online 8-17 UTC on weekdays, so I should be relatively quick in replying to pings during that period.


(I am a mentor of [the other packit task](https://pagure.io/mentored-projects/issue/69).)

**Comment by rishavanand** [comment]
@jpopelka Is there any way I can help to store data in Postgresql instead of abusing Redis?

**Comment by jpopelka** [comment]
@rishavanand I'm not sure where we actually are in the process of moving from Redis to Postgresql.
We have a ticket for the migration in our internal tracking tool and no one is going to work on that at least in the following 2 weeks, so there is space for you to work on that.
However, it first needs some design. We don't want to blindly migrate all data as they are, but we first
need to decide what do we really want to store in the tables and how they will be related - and that probably needs someone who is already familiar with the service internals.

Maybe @TomasTomecek could help us with the decision here? Tomas, do you think there's something that @rishavanand could help us with regarding the Redis 2 Postgres move?

**Comment by TomasTomecek** [comment]
well yeah, get into packit service repo, open the rest api code and start replacing redis calla with psql calls, I can create a more precise issue once in front of a real pc

**Comment by rishavanand** [comment]
thanks @TomasTomecek on the issue already.

**Comment by pulkitrissam10** [comment]
@dhodovsk can i work on this issue ?

**Comment by TomasTomecek** [comment]
I'd say this issue will get solved once we complete https://github.com/packit-service/packit-service/issues/459
