### ISSUE TITLE
Use icons for git forges

### ISSUE THREAD

**Issue by IceWreck** [packit/dashboard#54]
- the forge icon at /projects/... is hardcoded to github right now, replace it with the correct one
- Jobs view should also display git forge icon in every row

**Comment by TomasTomecek** [comment]
I can see that jobs have a github icon right now.

**Comment by IceWreck** [comment]
It also shows you a generic icon in case of git.stg.centos (no icon for pagure on patternfly :frowning_face: ) or anything else thats not github or gitlab.

**Comment by TomasTomecek** [comment]
> It also shows you a generic icon in case of git.stg.centos (no icon for pagure on patternfly frowning_face ) or anything else thats not github or gitlab.

I think that's good enough, for pagure, we can track that as an issue in the meantime.

**Comment by lachmanfrantisek** [comment]
What about closing it? Isn't the general one for Pagure enough? Or, do we want to convert it manually?
