### ISSUE TITLE
SRPM jobs: add datetime

### ISSUE THREAD

**Issue by TomasTomecek** [packit/dashboard#56]
I'd love to see a datetime of the SRPM build so that I know the timespan I am looking at.

**Comment by IceWreck** [comment]
Is that stored the in db right now? We will have to store it similar to copr_build_submitted_time.

We can also get a copr build associated to an SRPM Build and then get its time but idk if thats efficient or fast enough

**Comment by TomasTomecek** [comment]
> Is that stored the in db right now?

If it's not, we should definitely store that as an separate entry to know when packit-service is processing the SRPM.
