### ISSUE TITLE
Better PR and release icon

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#62]
I've been a bit confused about the PR icon in the project list.

![Screenshot from 2020-11-04 09-30-52](https://user-images.githubusercontent.com/20214043/98087543-891da280-1e80-11eb-9f77-3e486b1f37bd.png)

What about something like this?

![](https://img.icons8.com/windows/452/pull-request.png)

And we can maybe use [`fa-tag`/`fa-tags`](https://fontawesome.com/v4.7.0/icon/tags) for release.

Or maybe something like `upgrade`:
![](https://img.icons8.com/small/72/buy-upgrade.png)

**Comment by IceWreck** [comment]
We are currently using icons from https://www.patternfly.org/v4/guidelines/icons/

While searching for icons, I couldn't find suitable ones for PRs and releases. But Patternfly does have a 'tags' icon which we can use for releases. 

Can you look at this list and see if you find a suitable one. If not I'll manually import the SVG for the PR icon.

**Comment by lachmanfrantisek** [comment]
@IceWreck Thanks!

What about `fa-arrow-circle-up` or `pf-icon-bundle`/`pf-icon-package` for release?

You are right, there is nothing for the PR, can you please import the svg so we have something like we are used to on GitHub?

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by lachmanfrantisek** [comment]
I still find this useful:

- [ ] Use `fa-arrow-circle-up` or `pf-icon-bundle`/`pf-icon-package` for release. (Others, what do you prefer?)
- [ ] Convert or find a better icon for pull-requests.

**Comment by TomasTomecek** [comment]
I'm wondering if we could use our Red Hat branded icons, thought I couldn't find any which are related to git :/

I also used an icon for my blog from this site (which are free to use w/ attribution): https://www.flaticon.com/free-icon/triple-arrow-merging-to-one_33290?term=merge&page=4&position=78&page=4&position=78&related_id=33290&origin=search

we could e.g. use
![](https://www.flaticon.com/svg/vstatic/svg/33/33290.svg?token=exp=1616578804~hmac=623894c67a3027b0e5d3d733322448e8)

Another great source of icons is https://thenounproject.com/
