### ISSUE TITLE
Ignore projects without any handled item

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#63]
Most of the project on the projects page is irrelevant because they don't handle any pr/issue/branch/release.

What about skipping those projects (they don't bring any value)? Or adding some option to opt-in/opt-out from listing them.

**Comment by IceWreck** [comment]
I see two options here,
a) handling this in the query in service
b) hiding the projects which have 0 PRs && 0 Branches handled

the second one would be easier and would allow us to add a toggle to opt-in/opt-out from viewing them

**Comment by lachmanfrantisek** [comment]
I am for the second one because of the reason you described.

Just a detail, I would count also issues and releases (so all four numbers we show have to be zero).

off-topic: It might sound picky from me to create multiple issues here, but I would like to say it's really cool that we have the dashboard! (I needed to contact our users and was glad that I can use dashboard instead of the database..;)

**Comment by lachmanfrantisek** [comment]
Thanks @IceWreck !

**Comment by lachmanfrantisek** [comment]
This is solved, isn't it?

Only the last point (`Add toggle to view ignored projects (later)`) is missing and will be done later.
