### ISSUE TITLE
Home page is empty

### ISSUE THREAD

**Issue by johannbg** [packit/dashboard#75]
There is no content being displayed on the dashboard other than "Dashboard Page Title" which is kinda useless...
![packit-dashboard-home](https://user-images.githubusercontent.com/1309070/109181994-70652f80-7784-11eb-83a6-f6cfbc43910d.png)

**Comment by TomasTomecek** [comment]
Agreed! I personally go to "Jobs" most of the time, not sure if that view should be the default. Also "Projects" could be a good initial view.

Where do others usually go?

**Comment by johannbg** [comment]
There is little value for individuals or teams to know about every job ( and then some since filters aren't working properly ) packit is performing but as a landing page some statistic information and or overall job page might be useful.

What's the initial scope of the dashboard part of the project? 
( is it thought as just somekind of information radiator or configuration platform of some sort? Or only meant for the packit team?  ) 

What value does it bring to me as a packit consumer to be using it?

**Comment by lachmanfrantisek** [comment]
@johannbg You are right. It does not look nice. We want to add some statistics/status/charts/... there. Sadly, the dashboard wasn't a high priority in the last months.

> What's the initial scope of the dashboard part of the project?

Originally, it was created as a companion to our result pages. I would say a nice view of our database.
It was done as a GSOC project ([task description](https://docs.fedoraproject.org/en-US/mentored-projects/gsoc/2020/ideas/#_dashboard_for_packit)).

> What value does it bring to me as a packit consumer to be using it?

You can see what was managed for your (or someone else's) project from one place. Yes, not so interesting for our users.
But nowadays, we (ok, mainly @IceWreck..;) are working on replacing the old result pages and having them incorporated into the dashboard (#73). And that will bring a real benefit to our users.

So the short-term plan (#71):
* Have a result page for build/test that can be linked from PR status. (Includes links to copr/koji, logs, installation instructions...)
* The pages are linked together (build/srpm/test-run/PR/project) for better browsing.

And long-term:
* Basic statistics.
* Deployment status and reporting of the problems on our side.
* Ideally, incorporate GitHub accounts and project management (e.g. to retrigger the job).

**Comment by TomasTomecek** [comment]
@lachmanfrantisek very good explanation - I'd say that right now the dashboard is really just a dashboard - overview what packit is doing with not many valuable info for users of packit - #73 will change it massively

Once we enable authentication via github and gitlab, the dashboard will start offering tailored info about projects you are working on, though we are definitely a few months away from that. In the meantime, github and gitlab are primary interfaces for packit.

**Comment by johannbg** [comment]
Will packit be limited to the Fedora/RHEL ecosystem or are there any "future" plans to allow it to be integrated with other distributions like (Open)Suse, Debian etc.

**Comment by TomasTomecek** [comment]
We don't have any plans to support other distributions right now - the main reason being that we don't know how those distributions work and no one requested such a thing from us so far.

**Comment by johannbg** [comment]
Not doing so you end up narrowing the packit end users base strictly to RH's own maintainers who are upstream and maintaining their component downstream, which begs the question why packit is not just RH internal tool,

**Comment by lachmanfrantisek** [comment]
To make some progress on the original issue, let's specify an outcome of this task:

* [ ] Provide a suggestion(s) about the possible look of the home page. (static text, links to docs, charts, statistics, last jobs, ...)
* [ ] Discuss the plan here and/or with the team.
* [ ] Implement the plan.

**Comment by mfocko** [comment]
Closed by #111, introduced links to documentation, GitHub namespace and contributing repository.
