### ISSUE TITLE
Project Page lacks filters 

### ISSUE THREAD

**Issue by johannbg** [packit/dashboard#76]
I'm pretty sure Adam Saleh story's are fascinating but regardless his storydrafts are not packaged in Fedora thus there needs to be means to filter such stuff out.  That said you will pretty fast exhaust all infra's resources if everything and everyone is allowed to use packit for anything so I recommend that packit is limited only to official teams/maintainers and their official maintained packages in the distribution. ( If packit takes off for real then you are talking about what 14k+ components that will be using it )
![packit-projects](https://user-images.githubusercontent.com/1309070/109185407-e0c18000-7787-11eb-953e-8a2196a6fe34.png)

**Comment by IceWreck** [comment]
Hey Jóhann, these are filtered. Projects that have packit-service enabled (perhaps the user enabled it for all of their repos) but haven't ever touched packit at all are already hidden in the dashboard. 

Some projects might have accidentally interacted with packit like the ones you pointed out, those are still visible.

As for the rest of what you suggested, someone from the Packit team will hopefully reply soon.

**Comment by lachmanfrantisek** [comment]
@IceWreck thank you for answering the filtering part. You are right.
It was originally requested by me in #63 and implemented by @IceWreck. Not sure if we can easily filter by a better rule than "at least one activity we have reacted on".

@johannbg Regarding the proposal about being strictly Fedora only, that's a different topic and much harder to answer, but thanks for creating the issue.
* We do manual approval and require `Fedora Project Contributor Agreement ` for now. (We can make this step more strict if needed.) (For others, the onboarding has been discussed a bit in this issue: packit/packit-service#997)
* For projects without proper Packit setup (=i.e. config file), we don't spend a lot of resources. (Really minimal comparing to regular workflows.)
* We are still in a phase that we are happy for new users and trying to ease the onboarding as much as possible. (Yes, it can change and we need to be prepared before the state we can't handle all repositories.)
* There is also some chance that by using Packit, some project will join the Fedora ecosystem.

@packit/the-packit-team can we discuss this tomorrow at our architecture meeting, please?

**Comment by lachmanfrantisek** [comment]
I think we can close this issue -- we already ignore projects without any activity and for special requests regarding searching/filtering, we can create a dedicated issue if needed (e.g. #61).
