### ISSUE TITLE
It would be nice to have timestamps on the test jobs page (at least)

### ISSUE THREAD

**Issue by thrix** [packit/dashboard#80]
Without timestamps it is hard to tell when the jobs run, which can be handy.

https://dashboard.packit.dev/jobs

**Comment by lachmanfrantisek** [comment]
Sadly, we don't have this info in the database yet. I'm creating an issue for that: packit/packit-service#1015

**Comment by lachmanfrantisek** [comment]
Just implemented the API part in packit-service.

**Comment by mfocko** [comment]
Just had a look at prod API, it seems everywhere is `null` for the submitted time.
