### ISSUE TITLE
Link Copr build result page from the test result page

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/dashboard#99]
Here is the current state of the test result page:

![Screenshot from 2021-04-27 09-36-31](https://user-images.githubusercontent.com/20214043/116203626-2c6ab880-a73c-11eb-9fa9-952051079d89.png)

For comparison, in the Copr build result page, we have a link for an SRPM result page:

![Screenshot from 2021-04-27 09-36-48](https://user-images.githubusercontent.com/20214043/116203893-781d6200-a73c-11eb-81d2-d44ef0d1e644.png)

The task here is to:
- [ ] enhance the packit API if needed
- [ ] show the Copr build link in the details section

**Comment by mfocko** [comment]
Whoops, this is done, fixed by #100
